// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models
{
    public partial class ColorCategory
    {
        public ColorCategory()
        {
            ProductGroups = new HashSet<ProductGroup>();
        }

        public int ColorId { get; set; }
        public string ColorName { get; set; }

        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
    }
}